services:
  - type: web
    name: django-tutorial
    env: python
    plan: free
    rootDir: mysite
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mysite.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PUBLIC_DOMAIN
        fromService:
          type: web
          name: django-tutorial
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: django-tutorial-db
          property: connectionString

databases:
  - name: django-tutorial-db
    plan: free
